version: '3.8'

services:

  open-search: # This is also the hostname of the container within the Docker network (i.e. https://open-search/)
    image: opensearchproject/opensearch:2.12.0
    container_name: open-search
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true                               Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"          #       Set min and max JVM heap sizes to at least 50% of system RAM
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      #      - node.name=open-search                                    Name the node that will run in this container

      # - cluster.name=opensearch-cluster                          Name the cluster
      #- discovery.seed_hosts=open-search                            Nodes to look for when discovering the cluster
      #- cluster.initial_cluster_manager_nodes=open-search           Nodes eligibile to serve as cluster manager
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Ram0Khum0@1992        # Sets the demo admin user password when using demo configuration (for OpenSearch 2.12 and later)
    ulimits:
      memlock:
        soft: -1                                                # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536                                             # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - open-search-vol-data:/usr/share/opensearch/data             # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200   # REST API
      - 9600:9600   # Performance Analyzer
    networks:
      - open-recruitmentzone                                       # All of the containers will join the same Docker bridge network

networks:
  open-recruitmentzone:
    external: true

volumes:
  open-search-vol-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jenkins/open-search-volume/data

